
# this is fake, but texlive or "shell only" is not officially supported
language: c

compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y texlive texlive-lang-german texlive-most 
script: make
